///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class MakaleModelData {
/*
{
  "makale_adi": "Dart Dilinde Nesne Tabanlı Programlama",
  "yazar": "Emirhan Soylu",
  "id": 1,
  "yayin_tarihi": "30/03/2024",
  "aciklama": "Dart dilinde nesne tabanlı programlamayı çok açıklayıcı bir şekilde öğrenebileceksiniz.",
  "kategori": "Flutter"
}
*/

  String? makaleAdi;
  String? yazar;
  int? id;
  String? yayinTarihi;
  String? aciklama;
  String? kategori;

  MakaleModelData({
    this.makaleAdi,
    this.yazar,
    this.id,
    this.yayinTarihi,
    this.aciklama,
    this.kategori,
  });
  MakaleModelData.fromJson(Map<String, dynamic> json) {
    makaleAdi = json['makale_adi']?.toString();
    yazar = json['yazar']?.toString();
    id = json['id']?.toInt();
    yayinTarihi = json['yayin_tarihi']?.toString();
    aciklama = json['aciklama']?.toString();
    kategori = json['kategori']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['makale_adi'] = makaleAdi;
    data['yazar'] = yazar;
    data['id'] = id;
    data['yayin_tarihi'] = yayinTarihi;
    data['aciklama'] = aciklama;
    data['kategori'] = kategori;
    return data;
  }
}

class MakaleModel {
/*
{
  "data": [
    {
      "makale_adi": "Dart Dilinde Nesne Tabanlı Programlama",
      "yazar": "Emirhan Soylu",
      "id": 1,
      "yayin_tarihi": "30/03/2024",
      "aciklama": "Dart dilinde nesne tabanlı programlamayı çok açıklayıcı bir şekilde öğrenebileceksiniz.",
      "kategori": "Flutter"
    }
  ]
}
*/

  List<MakaleModelData?>? data;

  MakaleModel({
    this.data,
  });
  MakaleModel.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <MakaleModelData>[];
      v.forEach((v) {
        arr0.add(MakaleModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
